<?php
namespace Gridonic\ESR;
require __DIR__ . '/../../../vendor/autoload.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-04 at 18:39:52.
 */
class SwissInpaymentSlipTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var SwissInpaymentSlip
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
		$slipData = new SwissInpaymentSlipData();
        $this->object = new SwissInpaymentSlip($slipData);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::getInpaymentSlipData
     * @todo   Implement testGetInpaymentSlipData().
     */
    public function testGetInpaymentSlipData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::setSlipPosition
     * @todo   Implement testSetSlipPosition().
     */
    public function testSetSlipPosition()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::setSlipSize
     * @todo   Implement testSetSlipSize().
     */
    public function testSetSlipSize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::setSlipBackground
     * @todo   Implement testSetSlipBackground().
     */
    public function testSetSlipBackground()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::setBankLeftAttr
     * @todo   Implement testSetBankLeftAttr().
     */
    public function testSetBankLeftAttr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::setBankRightAttr
     * @todo   Implement testSetBankRightAttr().
     */
    public function testSetBankRightAttr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::setRecipientLeftAttr
     * @todo   Implement testSetRecipientLeftAttr().
     */
    public function testSetRecipientLeftAttr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::setRecipientRightAttr
     * @todo   Implement testSetRecipientRightAttr().
     */
    public function testSetRecipientRightAttr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::setAccountLeftAttr
     * @todo   Implement testSetAccountLeftAttr().
     */
    public function testSetAccountLeftAttr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::setAccountRightAttr
     * @todo   Implement testSetAccountRightAttr().
     */
    public function testSetAccountRightAttr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::setAmountFrancsLeftAttr
     * @todo   Implement testSetAmountFrancsLeftAttr().
     */
    public function testSetAmountFrancsLeftAttr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::setAmountFrancsRightAttr
     * @todo   Implement testSetAmountFrancsRightAttr().
     */
    public function testSetAmountFrancsRightAttr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::setAmountCentsLeftAttr
     * @todo   Implement testSetAmountCentsLeftAttr().
     */
    public function testSetAmountCentsLeftAttr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::setAmountCentsRightAttr
     * @todo   Implement testSetAmountCentsRightAttr().
     */
    public function testSetAmountCentsRightAttr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::setReferenceNumberLeftAttr
     * @todo   Implement testSetReferenceNumberLeftAttr().
     */
    public function testSetReferenceNumberLeftAttr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::setReferenceNumberRightAttr
     * @todo   Implement testSetReferenceNumberRightAttr().
     */
    public function testSetReferenceNumberRightAttr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::setPayerLeftAttr
     * @todo   Implement testSetPayerLeftAttr().
     */
    public function testSetPayerLeftAttr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::setPayerRightAttr
     * @todo   Implement testSetPayerRightAttr().
     */
    public function testSetPayerRightAttr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::setCodeLineAttr
     * @todo   Implement testSetCodeLineAttr().
     */
    public function testSetCodeLineAttr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::getAccountLeftAttr
     * @todo   Implement testGetAccountLeftAttr().
     */
    public function testGetAccountLeftAttr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::getAccountRightAttr
     * @todo   Implement testGetAccountRightAttr().
     */
    public function testGetAccountRightAttr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::getAmountCentsRightAttr
     * @todo   Implement testGetAmountCentsRightAttr().
     */
    public function testGetAmountCentsRightAttr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::getAmountCentsLeftAttr
     * @todo   Implement testGetAmountCentsLeftAttr().
     */
    public function testGetAmountCentsLeftAttr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::getAmountFrancsLeftAttr
     * @todo   Implement testGetAmountFrancsLeftAttr().
     */
    public function testGetAmountFrancsLeftAttr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::getAmountFrancsRightAttr
     * @todo   Implement testGetAmountFrancsRightAttr().
     */
    public function testGetAmountFrancsRightAttr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::getBankLeftAttr
     * @todo   Implement testGetBankLeftAttr().
     */
    public function testGetBankLeftAttr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::getBankRightAttr
     * @todo   Implement testGetBankRightAttr().
     */
    public function testGetBankRightAttr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::getCodeLineAttr
     * @todo   Implement testGetCodeLineAttr().
     */
    public function testGetCodeLineAttr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::getRecipientRightAttr
     * @todo   Implement testGetRecipientRightAttr().
     */
    public function testGetRecipientRightAttr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::getRecipientLeftAttr
     * @todo   Implement testGetRecipientLeftAttr().
     */
    public function testGetRecipientLeftAttr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::getPayerRightAttr
     * @todo   Implement testGetPayerRightAttr().
     */
    public function testGetPayerRightAttr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::getPayerLeftAttr
     * @todo   Implement testGetPayerLeftAttr().
     */
    public function testGetPayerLeftAttr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::getReferenceNumberLeftAttr
     * @todo   Implement testGetReferenceNumberLeftAttr().
     */
    public function testGetReferenceNumberLeftAttr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::getReferenceNumberRightAttr
     * @todo   Implement testGetReferenceNumberRightAttr().
     */
    public function testGetReferenceNumberRightAttr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::getSlipBackground
     * @todo   Implement testGetSlipBackground().
     */
    public function testGetSlipBackground()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::getSlipHeight
     * @todo   Implement testGetSlipHeight().
     */
    public function testGetSlipHeight()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::getSlipPosX
     * @todo   Implement testGetSlipPosX().
     */
    public function testGetSlipPosX()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::getSlipPosY
     * @todo   Implement testGetSlipPosY().
     */
    public function testGetSlipPosY()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::getSlipWidth
     * @todo   Implement testGetSlipWidth().
     */
    public function testGetSlipWidth()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::setDisplayAccount
     * @todo   Implement testSetDisplayAccount().
     */
    public function testSetDisplayAccount()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::getDisplayAccount
     * @todo   Implement testGetDisplayAccount().
     */
    public function testGetDisplayAccount()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::setDisplayAmount
     * @todo   Implement testSetDisplayAmount().
     */
    public function testSetDisplayAmount()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::getDisplayAmount
     * @todo   Implement testGetDisplayAmount().
     */
    public function testGetDisplayAmount()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::setDisplayBank
     * @todo   Implement testSetDisplayBank().
     */
    public function testSetDisplayBank()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::getDisplayBank
     * @todo   Implement testGetDisplayBank().
     */
    public function testGetDisplayBank()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::setDisplayPayer
     * @todo   Implement testSetDisplayPayer().
     */
    public function testSetDisplayPayer()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::getDisplayPayer
     * @todo   Implement testGetDisplayPayer().
     */
    public function testGetDisplayPayer()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::setDisplayRecipient
     * @todo   Implement testSetDisplayRecipient().
     */
    public function testSetDisplayRecipient()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::getDisplayRecipient
     * @todo   Implement testGetDisplayRecipient().
     */
    public function testGetDisplayRecipient()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::setDisplayReferenceNr
     * @todo   Implement testSetDisplayReferenceNr().
     */
    public function testSetDisplayReferenceNr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::getDisplayReferenceNr
     * @todo   Implement testGetDisplayReferenceNr().
     */
    public function testGetDisplayReferenceNr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::setDisplayIban
     * @todo   Implement testSetDisplayIban().
     */
    public function testSetDisplayIban()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::getDisplayIban
     * @todo   Implement testGetDisplayIban().
     */
    public function testGetDisplayIban()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::setDisplayPaymentReason
     * @todo   Implement testSetDisplayPaymentReason().
     */
    public function testSetDisplayPaymentReason()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::getDisplayPaymentReason
     * @todo   Implement testGetDisplayPaymentReason().
     */
    public function testGetDisplayPaymentReason()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::setDisplayCodeLine
     * @todo   Implement testSetDisplayCodeLine().
     */
    public function testSetDisplayCodeLine()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::getDisplayCodeLine
     * @todo   Implement testGetDisplayCodeLine().
     */
    public function testGetDisplayCodeLine()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gridonic\ESR\SwissInpaymentSlip::getAllElements
     * @todo   Implement testGetAllElements().
     */
    public function testGetAllElements()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
